Repository southgard/ex_isbndb, pull requests merged in 2022-03, with the labels that each got.

#1 Testing in order to decide between Finch & HTTPoison
  lib/application.ex
  mix.exs
  mix.lock
Labels: enhancement

#2 Add ISBNdb Client
  lib/client.ex
  mix.exs
  mix.lock
  test/client_test.exs
  test/test_helper.exs
Labels: documentation, enhancement

#4 Add Author endpoints
  lib/author.ex
  lib/client.ex
  test/author_test.exs
Labels: documentation, enhancement

#5 Add coverage and test badges
  .github/workflows/elixir_workflow.yaml
  README.md
  mix.exs
  mix.lock
Labels: documentation

#7 Added tests for `ExIsbndb.Client`
  test/client_test.exs
Labels: enhancement

#8 Add Publisher endpoints
  lib/publisher.ex
  test/publisher_test.exs
Labels: documentation, enhancement

#11 Add Stats endpoints
  lib/stats.ex
  test/stats_test.exs
Labels: documentation, enhancement

#10 Add Search endpoints
  lib/search.ex
  test/search_test.exs
Labels: documentation, enhancement

#9 Feature/books endpoints
  lib/book.ex
  test/book_test.exs
Labels: documentation, enhancement

#12 Add Subject endpoints
  lib/subject.ex
  test/subject_test.exs
Labels: documentation, enhancement

#13 Delete `ExIsbndb` module
  lib/ex_isbndb.ex
  test/ex_isbndb_test.exs
Labels: enhancement

#14 Fix Coveralls badge
  README.md
Labels: documentation

#15 Added README documentation
  README.md
  mix.exs
Labels: documentation

#16 Feature/update coverage badge
  .github/workflows/elixir_workflow.yaml
  README.md
Labels: documentation

#17 Add package details
  mix.exs
Labels: documentation
